### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by samirdas** [Brainhack-Proceedings-2015/Villa_HBM_DIPY#3]
Interesting submission. Approved, but a couple of questions...

What I am curious about is how this relates to other kinds of segmentations. Are there any metrics of comparison... in terms of speed, reliability, accuracy? Also, as an example, you used 12 iterations. Is there a specific reason for this number?

**Comment by villalonreina** [comment]
This segmentation approach is very similar to the FSL-FAST and to the ANTS-Atropos implementations. They all belong to the family of Bayesian segmentation techniques. 
Regarding the metrics of comparison we compared our method to manually segmented brain labels from the IBSR dataset (http://www.nitrc.org/projects/ibsr) by using the Jaccard Index. This not only gave us the optimal parameters to run our implementation (i.e. number of iterations) but also allowed us to compare our results to the above mentioned software packages (FAST and Atropos).
