### ISSUE TITLE
Reviewer #2

### ISSUE THREAD

**Issue by ccraddock** [Brainhack-Proceedings-2015/Villa_HBM_DIPY#4]
how it was performed, and the results. What is the benefit of segmenting the dMRI data over just the T1 data? What features of the dMRI data were segmented (FA,MD,tractography)? Could you please also include the dMRI data in the figure? 

Please modify the first sentence to say something like "The objective of this project was to ..."

**Comment by villalonreina** [comment]
The benefit of segmenting a dMRI-derived scalar map are plenty. The most important one being that one avoids the registration step between the T1 and the dMRI. Also, dMRI segmentation on some scalar maps might give insight into different tissue arrangements in the brain, that are not evident in the T1 and might also help guide tractography to make it more accurate. In this particular case we not only tested our segmentation algorithm on T1-weighted images but also on a new type of dMRI-derived scalar map called Power-maps (please see reference in the paper). These scalar maps gives a tissue contrast very similar to a T1 image, with very distinct separable grey and white matter regions. We hypothesized that our algorithm would give us a 3-type tissue classification on a Power-map after which we could feed it into an ACT tractography (Anatomically Constrained Tractography) and produce meaningful tractograms.
